#!/usr/bin/env python3
"""Builds AuraFizz2D_Install.lua: one script to paste into the Studio Command Bar.
It creates/updates the modules with their Source, backing up old copies to
ServerStorage.AuraFizzRemoved (same convention as your AURAFIZZ updates).
Run after editing anything in src/:   python3 tools/build_installer.py
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
EQ = "=" * 8

def lit(s):
    assert ("]" + EQ + "]") not in s
    return "[" + EQ + "[\n" + s + "]" + EQ + "]"

mods = sorted(f[:-5] for f in os.listdir(os.path.join(SRC, "AuraFizz2D")) if f.endswith(".luau"))
out = ["--!nocheck",
       "-- AURAFIZZ · AuraFizz2D installer (Studio Command Bar, Edit mode)  GENERATED by tools/build_installer.py",
       "-- Paste this whole script into the Command Bar and press Enter. It adds the 2D gameplay GUI:",
       "--   ReplicatedStorage.AuraFizz2D           (ModuleScripts: Api, Cafe, MiniGames, Storage, ...)",
       "--   ServerScriptService.AuraFizz2DServer   (tips + orders; edit its Hooks for your economy)",
       "--   StarterPlayer.StarterPlayerScripts.AuraFizz2DClient  (open button, F key, server opens)",
       "-- It reads your existing ReplicatedStorage.Drinks modules and builds NO parts or models.",
       "-- Old copies go to ServerStorage.AuraFizzRemoved. Ctrl+Z undoes it. Safe to run again.",
       "",
       "local RS = game:GetService(\"ReplicatedStorage\")",
       "local SSS = game:GetService(\"ServerScriptService\")",
       "local SS = game:GetService(\"ServerStorage\")",
       "local SP = game:GetService(\"StarterPlayer\")",
       "local CHS = game:GetService(\"ChangeHistoryService\")",
       "CHS:SetWaypoint(\"AuraFizz2D install (before)\")",
       "local removed = SS:FindFirstChild(\"AuraFizzRemoved\") or Instance.new(\"Folder\")",
       "removed.Name = \"AuraFizzRemoved\"",
       "removed.Parent = SS",
       "local function put(class, name, parent, source)",
       "\tlocal old = parent:FindFirstChild(name)",
       "\tif old and old:IsA(class) and old.Source == source then return old end",
       "\tif old then old.Name = name .. \"_old_\" .. os.time(); old.Parent = removed end",
       "\tlocal s = Instance.new(class)",
       "\ts.Name = name",
       "\ts.Source = source",
       "\ts.Parent = parent",
       "\treturn s",
       "end",
       "local pkg = RS:FindFirstChild(\"AuraFizz2D\")",
       "if not (pkg and pkg:IsA(\"Folder\")) then",
       "\tif pkg then pkg.Parent = removed end",
       "\tpkg = Instance.new(\"Folder\")",
       "\tpkg.Name = \"AuraFizz2D\"",
       "\tpkg.Parent = RS",
       "end",
       ""]
for m in mods:
    src = open(os.path.join(SRC, "AuraFizz2D", m + ".luau"), encoding="utf-8").read()
    out.append(f'put("ModuleScript", "{m}", pkg, {lit(src)})')
server = open(os.path.join(SRC, "server", "AuraFizz2D.server.luau"), encoding="utf-8").read()
client = open(os.path.join(SRC, "client", "AuraFizz2D.client.luau"), encoding="utf-8").read()
out.append(f'put("Script", "AuraFizz2DServer", SSS, {lit(server)})')
out.append(f'put("LocalScript", "AuraFizz2DClient", SP:WaitForChild("StarterPlayerScripts"), {lit(client)})')
out += ["",
        "CHS:SetWaypoint(\"AuraFizz2D install\")",
        "local drinks = RS:FindFirstChild(\"Drinks\")",
        "print(\"[AuraFizz2D] installed \" .. #pkg:GetChildren() .. \" modules.\" .. (drinks and \" Found ReplicatedStorage.Drinks.\" or \" WARNING: ReplicatedStorage.Drinks not found - install your AURAFIZZ drink modules first.\"))",
        ""]
path = os.path.join(ROOT, "AuraFizz2D_Install.lua")
open(path, "w", encoding="utf-8").write("\n".join(out))
print("wrote", path, sum(1 for _ in open(path, encoding="utf-8")), "lines")
